name: python lint
on: [push]
jobs:
  sdk-python-lint:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: lint with black
        uses: psf/black@stable
        with:
          options: "-l 120 --check --verbose --diff"
          src: .
          version: "23.7.0"

      - name: lint with flake8
        uses: py-actions/flake8@v2
        with:
          args: --max-line-length=120
          flake8-version: "6.0.0"
          path: "."
